services:
  # Backend API Service
  agentstore-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: agentstore-api
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-prod}
      # Database configuration using your external PostgreSQL
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DB_HOST:-your-server-ip}:${DB_PORT:-5432}/${DB_NAME:-agentstoreDB}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME:-depo}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD:-Kawasaki@007}
      - JWT_SECRET=${JWT_SECRET:-5b96d669681c4a7682d399455a7aa8e2d657bb43bc384c528ba3fdf5170324d9}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-http://localhost:3000,http://localhost:80}
    ports:
      - "8080:8080"
    networks:
      - agentstore-network
    restart: unless-stopped

  # Frontend Service
  agentstore-frontend:
    build:
      context: ./agent-store-dashboard-ui
      dockerfile: Dockerfile
    container_name: agentstore-frontend
    ports:
      - "80:80"
    networks:
      - agentstore-network
    restart: unless-stopped
    depends_on:
      - agentstore-api

networks:
  agentstore-network:
    driver: bridge 