spring:
  application:
    name: agentstore-api
  profiles:
    active: @spring.profiles.active@
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/agentstoreDB
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8080
  servlet:
    context-path: /api/v1

# JWT Configuration
app:
  jwt:
    secret: ${JWT_SECRET:5b96d669681c4a7682d399455a7aa8e2d657bb43bc384c528ba3fdf5170324d9}
    expiration: 86400000  # 24 hours
    refresh-expiration: 604800000  # 7 days
    issuer: agentstore
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    enabled: true
  default-produces-media-type: application/json 