spring:
  security:
    enabled: false
  jpa:
    show-sql: true
  flyway:
    clean-disabled: false
    clean-on-validation-error: true

logging:
  level:
    org.springframework.security: DEBUG
    com.agentstore.api: DEBUG
    org.hibernate.SQL: DEBUG

# Override for development environment
app:
  cors:
    allowed-origins: http://localhost:3007