services:
  postgres:
    image: postgres:16
    container_name: postgresDB
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agentstoreDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - agentstore-network
    restart: unless-stopped

volumes:
  postgres_data:
    name: agentstore-postgres-data

networks:
  agentstore-network:
    name: agentstore-network
