services:
  # postgres:
  #   image: postgres:16
  #   container_name: postgres
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: postgres
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - agentstore-network
  #   restart: unless-stopped

  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: depoApps-api
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=dev
  #     - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/agentstoreDB
  #     - SPRING_DATASOURCE_USERNAME=depo
  #     - SPRING_DATASOURCE_PASSWORD=Kawasaki@007
  #     - JWT_SECRET=5b96d669681c4a7682d399455a7aa8e2d657bb43bc384c528ba3fdf5170324d9
  #     - CORS_ALLOWED_ORIGINS=http://localhost:3007
  #   ports:
  #     - "8445:8445"
  #   networks:
  #     - agentstore-network
  #   restart: unless-stopped
    
