services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agentstore-api
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresDB:5432/agentstoreDB
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - JWT_SECRET=5b96d669681c4a7682d399455a7aa8e2d657bb43bc384c528ba3fdf5170324d9
      - CORS_ALLOWED_ORIGINS=http://localhost:3007
    ports:
      - "8445:8445"
    networks:
      - agentstore-network
    restart: unless-stopped

networks:
  agentstore-network:
    name: agentstore-network
    external: true 